steps:
  - id: build-image
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/sideu', '.']
  - id: push-image
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/sideu']


steps:
  - id: Build
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '$_GCR_HOSTNAME/${PROJECT_ID}/$REPO_NAME/siedu:latest',
      '--cache-from', '$_GCR_HOSTNAME/${PROJECT_ID}/$REPO_NAME/siedu:latest',
      '.'
    ]
  - id: Push
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_GCR_HOSTNAME/${PROJECT_ID}/$REPO_NAME/siedu:latest']
  - id: Deploy
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  _LABELS: gcb-trigger-id=d00a2849-f62b-42a9-8fc8-0525505f7a54
  _TRIGGER_ID: d00a2849-f62b-42a9-8fc8-0525505f7a54
  _PLATFORM: managed
  _SERVICE_NAME: siedu
